FROM node:22-alpine AS build-step
 
RUN yarn config set "strict-ssl" false -g
 
WORKDIR /app
 
ENV PATH /app/node_modules/.bin:$PATH
 
COPY package.json package.json
RUN npm install
 
COPY . .
RUN npm run build
 
FROM nginx:stable-alpine
COPY --from=build-step /app/dist /usr/share/nginx/html
COPY ./nginx.default.conf /etc/nginx/conf.d/default.conf